### ISSUE TITLE
Suggestion to allow using Java8 lambda notation as callbacks 

### ISSUE THREAD

**Issue by bauna** [tbroyer/promises#1]
Hi Thomas,
The library is really nice, although it doesn't feel right that we cannot use lambdas as callbacks. 
So my suggestion is change the Callback to be a FunctionalIterface that receives a Response that you can query to know if the promise is Fulfilled or Rejected.
Below a sketched an example:

``` java
public interface Promise<V> {

  interface Response<V, R> {
      boolean isFullfilled();
      V getValue();
      R getRejection();
  }

  class ExceptionReponse<V, R extends Throwable> implements Response<V, R> {
    private final R rejection;

    public ExceptionReponse(R rejection) {
        this.rejection = rejection;
    }

    @Override
    public boolean isFullfilled() {
        return false;
    }

    @Override
    public V getValue() {
        return null; //or throw an exception.
    }

    @Override
    public R getRejection() {
        return rejection;
    }
  }

  @FunctionalInterface
  interface Callback<V, R> {
    void onExecuted(Response<V, R> response);
  }

  ///..... change other methods accordingly .....
}
```

**Comment by tbroyer** [comment]
Sorry, I should have updated the README to state that this is an abandoned/deprecated project. I haven't worked on it for more than 3 years, and never actually put it to real use.

With Java 8, you should probably use `CompletionStage` instead of `Promise`, and `CompletableFuture` instead of `FulfillablePromise`; or you could use Guava's `ListenableFuture`, with a non-fluent API though.

BTW, to make this library lambda-friendly, I'd rather either have overloads taking two `Function`, or a `BiFunction` (similar to `CompletionStage#handle`), or a `Function` that would only be called when fulfilled with another method taking a `Function<Throwable>` that would only be called when rejected (similar to `CompletionStage#exceptionally`).

AFAICT, the one thing `CompletionStage` cannot do as easily (would require unwrapping a `CompletionStage` out of a `CompletionStage`) is handling an exceptional completion asynchronously, returning a `CompletionStage` (that could eventually complete normally).
